# Server configuraion
server:
  port: 9110

# Database Configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transcendence
      #username:
      #password:

# Kafka configuration
spring.cloud.stream.kafka:
  binder:
    brokers: localhost

# Channel configuration
spring.cloud.stream.bindings:
  output:
    destination: memberReqTopic
    content-type: application/json
  zhihu-member-callback:
    group: zhihu-member
  # Topic
  out-zhihu-topic-request:
    content-type: application/json
  in-zhihu-topic-callback-topic-page:
    group: zhihu-topic
  in-zhihu-topic-callback-topic:
    group: zhihu-topic
  in-zhihu-topic-callback-topic-list:
    group: zhihu-topic
  in-zhihu-topic-callback-plazza-list:
    group: zhihu-topic
  in-zhihu-topic-callback-feed-list:
    group: zhihu-topic
