server:
  port: 9101
spring:
  cloud:
    config:
      allowOverride: true
      server:
        git:
          uri: git@bitbucket.org:yan_h/transcendence.git
          clone-on-start: true
          force-pull: true
          delete-untracked-branches: true
          search-paths: config_repo
